In [112]:
import numpy as np
np.random.seed(0)

In [2]:
np.arange(2)

array([0, 1])

In [3]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a = np.arange(15).reshape(3, 5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [10]:
a.dtype

dtype('int32')

In [11]:
a.dtype.name

'int32'

In [12]:
a.itemsize

4

In [13]:
type(a)

numpy.ndarray

In [14]:
np.array([6, 7, 8])

array([6, 7, 8])

In [15]:
b=np.array([1.2, 3.5, 5.1])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([(1.5,2,3), (4,5,6)])

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones( (2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
np.empty( (2,3) ) 

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [21]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [22]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [23]:
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
np.linspace( 0, 2*np.pi,5)  

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [28]:
np.arange(12).reshape(4,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
print(np.arange(25).reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
np.arange( 4 )

array([0, 1, 2, 3])

In [31]:
np.arange( 4 )**2

array([0, 1, 4, 9], dtype=int32)

In [35]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [60]:
a = np.random.random((2,3))

In [61]:
a.sum()

4.18819375802254

In [62]:
a.min()

0.42010127789790264

In [63]:
a.max()

0.9748867413308784

In [64]:
a = np.arange(10)**3

In [65]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [66]:
a[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [67]:
a[:2]

array([0, 1], dtype=int32)

In [68]:
a[1]

1

In [69]:
a[4]

64

In [70]:
a[:4]

array([ 0,  1,  8, 27], dtype=int32)

In [71]:
a[4:]

array([ 64, 125, 216, 343, 512, 729], dtype=int32)

In [72]:
a[::]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [73]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [74]:
a[:5:]

array([ 0,  1,  8, 27, 64], dtype=int32)

In [75]:
a[:5]

array([ 0,  1,  8, 27, 64], dtype=int32)

In [77]:
a[::4]

array([  0,  64, 512], dtype=int32)

In [79]:
a[::2]

array([  0,   8,  64, 216, 512], dtype=int32)

In [82]:
a[-1]

729

In [83]:
a[:-1]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512], dtype=int32)

In [91]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype='int16')

In [92]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [89]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [96]:
np.random.random((3,4))

array([[0.45334045, 0.75998593, 0.66924147, 0.25186193],
       [0.94454039, 0.73329191, 0.25275401, 0.72297179],
       [0.87057745, 0.29132011, 0.24979066, 0.05478853]])

In [93]:
np.floor(10*np.random.random((3,4)))

array([[9., 7., 4., 4.],
       [5., 7., 0., 6.],
       [8., 7., 1., 9.]])

In [94]:
np.floor(10*np.random.random((2,2)))

array([[8., 8.],
       [7., 8.]])

In [97]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [106]:
a, "*************",b

(array([[9., 7.],
        [2., 7.]]), '*************', array([[3., 2.],
        [7., 2.]]))

In [98]:
np.vstack((a,b))

array([[9., 7.],
       [2., 7.],
       [3., 2.],
       [7., 2.]])

In [107]:
a = np.arange(12)
b = a            # no new object is created
b is a

True

In [108]:
a = np.arange(12).reshape(3,4)

In [110]:
b =a>4

In [111]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [116]:
x1 = np.random.randint(10, size=(3, 4, 5))

In [117]:
x1[0, 0]

array([3, 5, 2, 4, 7])

In [118]:
x=np.arange(10)

In [120]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [119]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])